#ifndef COEUR_H_INCLUDED
#define COEUR_H_INCLUDED
int led[10];
void InitialisationLed(int*); //Prototype de la fonction"InitialisastionLed"
void AllLed(int,int*); //Prototype de la fonction "AllLed" qui prendra le tableau led et la valeur de i (BPM)
void TwoLed(int,int*); //Même chose 
void ThreeLed(int,int*); //...
void FourLed(int,int*);//...
void FiveLed(int,int*);//...
void SixLed(int,int*);//...
void SevenLed(int,int*);//...
void EightLed(int,int*);//...
void NineLed(int,int*);//...
void OnlyLed(int,int*,int); //Ici, on rajoutera aussi la valeur "sel" utilisateur afin d'allumer la LED correspondante
void Chenille(int,int*);//...
void ChenilleB(int,int*);//...
void Simulateur(int,int*);//Ici on va récupérer le pouls demandé par l'utilisateur et le tableau led

#endif // COEUR_H_INCLUDED
